Feat: bookstore api
Amrhub/Bookstore pull request #3
Opened 2021-12-09 21:11 UTC by Amrhub

2021-12-09 21:25 UTC, Amrhub commented
note: `toShare` `another` commit were on a different branch and weren't intended :) I just merged and forgot about them

2021-12-09 22:33 UTC, cyonii requested changes
# Changes Required ♻️ 

Hi @Amrhub, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes
_Check the comments under the review to see the changes you need to make._
- [] Please keep your commit messages descriptive, commit messages like "toShare" and "another" doesn't describe the changes you made. Your commit messages should be able to describe what changes was made.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-09 22:33 UTC, cyonii commented on src/components/Books/AddBook.js
> +    e.target.category.value = '';
- [ ] I can add empty book without title or category. It would be nice to validate book data before creating a new book.

2021-12-09 22:33 UTC, cyonii commented on src/components/Books/BookButton.js
> +    dispatch(removeBookApi(bookId));
- [ ] I am unable to remove a book immediately after creating it. I would need to restart the browser first before I can delete them. Please fix this behavior

2021-12-10 00:14 UTC, Amrhub commented
@cyonii  Thanks for your feedback but if you read my comment you would have realized that comment messages were a mistake as mentioned :) other than that great changes requested

2021-12-10 00:21 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @Amrhub, 

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-10 09:58 UTC, merged